all:
	pdflatex Manuscript.tex
	bibtex Manuscript
	pdflatex Manuscript.tex
	pdflatex Manuscript.tex
clean:
	rm *.bbl *.blg *.mtc *.mtc0 *.mtc1 *.mtc2 *.mtc3 *.mtc4 *.out *.aux *.brf *.log *.maf *.toc Manuscript.pdf