all:
	pdflatex Manuscrit.tex
	bibtex Manuscrit
	pdflatex Manuscrit.tex
	pdflatex Manuscrit.tex
clean:
	rm *.bbl *.blg *.mtc *.mtc0 *.mtc1 *.mtc2 *.mtc3 *.mtc4 *.out *.aux *.brf *.log *.maf *.toc Manuscrit.pdf